# conf/config.yaml
defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# training / bo parameter
epochs: 15
seeds: [0, 1, 2, 3, 4]  
n_total: 2        
n_sobol: 1    
bound:
  low: 1e-4
  high: 1e-1



batch_size: 64
val_ratio: 0.2  # ratio between training and validation

device: "mps"      # or "cuda" / "cpu"
